In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.simplefilter('ignore')

In [2]:
df = pd.read_csv('/content/creditcard.csv')

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
df.shape

(23858, 31)

In [5]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [6]:
df['Class'].value_counts()

Class
0.0    23769
1.0       88
Name: count, dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [10]:
legit.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [11]:
legit.shape

(23769, 31)

In [12]:
fraud.shape

(88, 31)

In [13]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,...,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000,23857.000000
mean,18212.752735,-0.239140,0.198854,0.727012,0.248615,-0.188483,0.082789,-0.132140,0.022931,0.499397,...,-0.041187,-0.137287,-0.038435,0.013626,0.127921,0.027504,0.013233,0.004932,73.976583,0.003689
std,11376.870334,1.894258,1.533094,1.724923,1.440968,1.439899,1.328187,1.334687,1.378403,1.274225,...,0.837224,0.644720,0.526298,0.588573,0.435896,0.520213,0.401059,0.267790,212.761278,0.060623
min,0.000000,-30.552380,-40.978852,-31.103685,-5.172595,-42.147898,-23.496714,-26.548144,-41.484823,-7.175097,...,-20.262054,-8.593642,-26.751119,-2.836627,-7.495741,-1.338556,-8.567638,-9.617915,0.000000,0.000000
25%,6624.000000,-0.959531,-0.376147,0.287923,-0.658467,-0.767699,-0.663735,-0.595323,-0.167626,-0.330842,...,-0.253910,-0.561223,-0.173814,-0.325615,-0.134460,-0.337167,-0.066242,-0.009446,5.990000,0.000000
50%,20563.000000,-0.288672,0.192438,0.874370,0.216275,-0.218399,-0.179894,-0.066378,0.027189,0.422438,...,-0.104847,-0.110305,-0.048570,0.064300,0.164769,-0.046463,0.006465,0.020002,18.040000,0.000000
75%,29008.000000,1.164879,0.842817,1.505477,1.122372,0.325179,0.474159,0.450342,0.286125,1.261527,...,0.066320,0.273088,0.074189,0.400535,0.407827,0.314884,0.094960,0.077392,66.000000,0.000000
max,32954.000000,1.960497,16.713389,4.101716,11.927512,34.099309,22.529298,36.677268,20.007208,10.392889,...,22.614889,5.805795,13.876221,3.695503,5.525093,3.517346,11.135740,4.860769,7879.420000,1.000000

In [14]:
legit.Amount.describe()

count    23769.000000
mean        73.880199
std        212.541174
min          0.000000
25%          6.000000
50%         18.110000
75%         65.850000
max       7879.420000
Name: Amount, dtype: float64

In [15]:
fraud.Amount.describe()

count      88.000000
mean      100.010000
std       265.845031
min         0.000000
25%         1.000000
50%         1.000000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [16]:
#compare the values for both transactions
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,18213.77782,-0.208135,0.175983,0.774952,0.226463,-0.166866,0.092304,-0.101868,0.006906,0.512306,...,0.038311,-0.043337,-0.136382,-0.037279,0.014613,0.127111,0.02694,0.010111,0.004578,73.880199
1.0,17935.87500,-8.613716,6.376169,-12.221731,6.231847,-6.027247,-2.487080,-8.308784,4.351326,-2.987199,...,0.714069,0.539387,-0.381823,-0.350615,-0.252970,0.346695,0.17976,0.856336,0.100578,100.010000

**Under Sampling**

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [17]:
legit_sample = legit.sample(n=492)

In [18]:
df = pd.concat([legit_sample,fraud],axis=0)

In [19]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
12538,21940,1.302643,-0.465118,0.788434,-0.414847,-1.085432,-0.719777,-0.720332,-0.131308,0.565153,...,-0.190552,-0.465660,0.205295,0.311078,0.063991,-0.511090,-0.007329,0.018702,29.90,0.0
3397,2922,-0.621329,0.775998,0.951563,-2.131745,0.227349,-1.072073,1.024577,-0.240966,1.159067,...,0.048500,0.571776,-0.243470,0.050315,0.020344,-0.802214,0.354170,0.040992,1.00,0.0
19375,30227,-0.680111,0.010671,1.238921,1.965315,0.274440,-0.031944,0.452723,0.101432,-0.343622,...,0.138763,0.309374,0.282831,0.077404,-0.396547,-0.175363,0.171282,0.190223,118.00,0.0
6087,6945,-0.927028,0.977478,0.752801,-0.812418,1.538866,0.390491,1.051882,0.035946,0.670651,...,-0.581156,-1.436950,-0.040954,-1.475637,0.036843,-1.138072,0.156363,0.060234,61.98,0.0
4424,3768,-1.411559,0.314501,1.695915,-1.655081,-0.418470,-0.271195,-0.257594,0.545201,-0.579671,...,-0.057815,-0.327560,0.026758,-0.071212,0.240760,-0.578364,0.122927,-0.003960,59.31,0.0

In [20]:
df.shape

(580, 31)

In [21]:
df['Class'].value_counts()

Class
0.0    492
1.0     88
Name: count, dtype: int64

**Splitting the Data**

In [22]:
X = df.drop('Class',axis=1)
Y = df['Class']

In [23]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
12538  21940  1.302643 -0.465118  0.788434 -0.414847 -1.085432 -0.719777
3397    2922 -0.621329  0.775998  0.951563 -2.131745  0.227349 -1.072073
19375  30227 -0.680111  0.010671  1.238921  1.965315  0.274440 -0.031944
6087    6945 -0.927028  0.977478  0.752801 -0.812418  1.538866  0.390491
4424    3768 -1.411559  0.314501  1.695915 -1.655081 -0.418470 -0.271195
...      ...       ...       ...       ...       ...       ...       ...
18773  29753  0.269614  3.549755 -5.810353  5.809370  1.538808 -2.269219
18809  29785  0.923764  0.344048 -2.880004  1.721680 -3.019565 -0.639736
20198  30852 -2.830984  0.885657  1.199930  2.861292  0.321669  0.289966
23308  32686  0.287953  1.728735 -1.652173  3.813544 -1.090927 -0.984745
23422  32745 -2.179135  0.020218 -2.182733  2.572046 -3.663733  0.081568

             V7        V8        V9  ...       V20       V21       V22  \
12538 -0.720332 -0.131308  0.565153  ... -0.010001 -0.190552 -0.465660
3397   1.024577 -0.240966  1.159067  ...  0.069750  0.048500  0.571776
19375  0.452723  0.101432 -0.343622  ...  0.407226  0.138763  0.309374
6087   1.051882  0.035946  0.670651  ... -0.144289 -0.581156 -1.436950
4424  -0.257594  0.545201 -0.579671  ...  0.288235 -0.057815 -0.327560
...         ...       ...       ...  ...       ...       ...       ...
18773 -0.824203  0.351070 -3.759059  ...  0.310525  0.371121 -0.322290
18809 -3.801325  1.299096  0.864065  ...  0.170872  0.899931  1.481271
20198  1.767760 -2.451050  0.069736  ... -1.016923  0.546589  0.334971
23308 -2.202318  0.555088 -2.033892  ...  0.265250  0.262202 -0.633528
23422  0.268049  0.660437 -2.374027  ...  1.957960  1.026421  0.299614

            V23       V24       V25       V26       V27       V28  Amount
12538  0.205295  0.311078  0.063991 -0.511090 -0.007329  0.018702   29.90
3397  -0.243470  0.050315  0.020344 -0.802214  0.354170  0.040992    1.00
19375  0.282831  0.077404 -0.396547 -0.175363  0.171282  0.190223  118.00
6087  -0.040954 -1.475637  0.036843 -1.138072  0.156363  0.060234   61.98
4424   0.026758 -0.071212  0.240760 -0.578364  0.122927 -0.003960   59.31
...         ...       ...       ...       ...       ...       ...     ...
18773 -0.549856 -0.520629  1.378210  0.564714  0.553255  0.402400    0.68
18809  0.725266  0.176960 -1.815638 -0.536517  0.489035 -0.049729   30.30
20198  0.172106  0.623590 -0.527114 -0.079215 -2.532445  0.311177  104.81
23308  0.092891  0.187613  0.368708 -0.132474  0.576561  0.309843    0.00
23422  1.656800  0.328433  0.106457  0.691775  0.196779  0.241085  717.15

[580 rows x 30 columns]

In [24]:
print(Y)

12538    0.0
3397     0.0
19375    0.0
6087     0.0
4424     0.0
        ...
18773    1.0
18809    1.0
20198    1.0
23308    1.0
23422    1.0
Name: Class, Length: 580, dtype: float64

**Training and Testing**

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

**Model Evaluation**

In [27]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [28]:
def evaluate(true,predicted):
  acc = accuracy_score(true,predicted)
  pre = precision_score(true,predicted)
  rec = recall_score(true,predicted)
  f1 = f1_score(true,predicted)

  return acc,pre,rec,f1

**Model Training**

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier

from sklearn.model_selection import cross_val_score

In [30]:
models = [LogisticRegression(),SVC(),KNeighborsClassifier(),DecisionTreeClassifier(),RandomForestClassifier(),XGBClassifier(),GradientBoostingClassifier(),AdaBoostClassifier()]

In [31]:
for model in models:
  model.fit(X_train,Y_train)

  Y_train_pred = model.predict(X_train)
  Y_test_pred = model.predict(X_test)

  acc,pre,rec,f1 = evaluate(Y_train,Y_train_pred)

  print("Model Name:",model)

  print()

  print("Training Results:")
  print("Accuracy:",acc)
  print("Precision:",pre)
  print("Recall:",rec)
  print("F1 Score:",f1)

  print()

  print("Testing Results:")
  print("Accuracy:",acc)
  print("Precision:",pre)
  print("Recall:",rec)
  print("F1 Score:",f1)

  print()
  cv_score = cross_val_score(model,X,Y,cv=5)
  print("Cross Validation:",cv_score)
  print("Cross Validation Score:",cv_score.mean())

  print("---------------------------------------------------------------------------")

Model Name: LogisticRegression()

Training Results:
Accuracy: 0.978448275862069
Precision: 0.9411764705882353
Recall: 0.9142857142857143
F1 Score: 0.927536231884058

Testing Results:
Accuracy: 0.978448275862069
Precision: 0.9411764705882353
Recall: 0.9142857142857143
F1 Score: 0.927536231884058

Cross Validation: [0.98275862 0.98275862 0.97413793 0.97413793 0.93965517]
Cross Validation Score: 0.9706896551724139
---------------------------------------------------------------------------
Model Name: SVC()

Training Results:
Accuracy: 0.8491379310344828
Precision: 0.0
Recall: 0.0
F1 Score: 0.0

Testing Results:
Accuracy: 0.8491379310344828
Precision: 0.0
Recall: 0.0
F1 Score: 0.0

Cross Validation: [0.85344828 0.85344828 0.84482759 0.84482759 0.84482759]
Cross Validation Score: 0.8482758620689657
---------------------------------------------------------------------------
Model Name: KNeighborsClassifier()

Training Results:
Accuracy: 0.8857758620689655
Precision: 0.6808510638297872
Recall: 0.45714285714285713
F1 Score: 0.5470085470085471

Testing Results:
Accuracy: 0.8857758620689655
Precision: 0.6808510638297872
Recall: 0.45714285714285713
F1 Score: 0.5470085470085471

Cross Validation: [0.81896552 0.81034483 0.79310345 0.8362069  0.74137931]
Cross Validation Score: 0.8
---------------------------------------------------------------------------
Model Name: DecisionTreeClassifier()

Training Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Testing Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Cross Validation: [0.96551724 0.97413793 0.88793103 0.93965517 0.97413793]
Cross Validation Score: 0.9482758620689655
---------------------------------------------------------------------------
Model Name: RandomForestClassifier()

Training Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Testing Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Cross Validation: [0.98275862 1.         0.97413793 0.97413793 0.98275862]
Cross Validation Score: 0.9827586206896551
---------------------------------------------------------------------------
Model Name: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

Training Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Testing Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Cross Validation: [0.97413793 0.99137931 0.97413793 0.98275862 0.96551724]
Cross Validation Score: 0.9775862068965517
---------------------------------------------------------------------------
Model Name: GradientBoostingClassifier()

Training Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Testing Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Cross Validation: [0.96551724 0.98275862 0.97413793 0.99137931 0.98275862]
Cross Validation Score: 0.9793103448275862
---------------------------------------------------------------------------
Model Name: AdaBoostClassifier()

Training Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Testing Results:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

Cross Validation: [0.98275862 0.99137931 0.97413793 0.99137931 0.94827586]
Cross Validation Score: 0.9775862068965516
---------------------------------------------------------------------------

**Hyper Parameter Tuning**

In [32]:
gb_params = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 5, 7],
    "subsample": [0.6, 0.8, 1.0],
    "max_features": ["sqrt", "log2",None]
}

In [33]:
random_cv = [
    ("GB", GradientBoostingClassifier(), gb_params)
]

In [34]:
from sklearn.model_selection import RandomizedSearchCV

In [35]:
model_params = {}

for name,model,params in random_cv:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=params,
                                verbose = 2,
                                n_jobs= -1,
                               n_iter=10,
                               )
    random.fit(X_train,Y_train)
    model_params[name] = random.best_params_
for model_name in model_params:
    print(f"--------------------Best Paarams for {model_name}-------------------")
    print(model_params[model_name])

Fitting 5 folds for each of 10 candidates, totalling 50 fits
--------------------Best Paarams for GB-------------------
{'subsample': 0.6, 'n_estimators': 200, 'max_features': None, 'max_depth': 5, 'learning_rate': 0.1}

In [36]:
model = random.best_estimator_

In [37]:
print(model)

GradientBoostingClassifier(max_depth=5, n_estimators=200, subsample=0.6)

In [38]:
model.fit(X_train,Y_train)

test_pred = model.predict(X_test)

acc = accuracy_score(Y_test,test_pred)

print(acc)

0.9827586206896551

In [39]:
input_data = (0,-1.3598071336738,-0.0727811733098497,2.53634673796914,1.37815522427443,-0.338320769942518,0.462387777762292,0.239598554061257,0.0986979012610507,0.363786969611213,0.0907941719789316,-0.551599533260813,-0.617800855762348,-0.991389847235408,-0.311169353699879,1.46817697209427,-0.470400525259478,0.207971241929242,0.0257905801985591,0.403992960255733,0.251412098239705,-0.018306777944153,0.277837575558899,-0.110473910188767,0.0669280749146731,0.128539358273528,-0.189114843888824,0.133558376740387,-0.0210530534538215,149.62)

input = np.asarray(input_data).reshape(1,-1)

prediction = model.predict(input)

print(prediction)

if prediction[0] == 0:
  print("Legitimate Transaction")
else:
  print("Fraudulent Transaction")

[0.]
Legitimate Transaction

In [40]:
import pickle

In [41]:
with open('card.sav','wb') as f:
  pickle.dump(model,f)

In [42]:
loaded = pickle.load(open('card.sav','rb'))